services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userscore
    ports:
      - "3307:3306"
    networks:
      - score_network
    volumes:
      - mysql_data:/var/lib/mysql

  userscore:
    image: "user-score"
    container_name: userscore
    depends_on:
      - mysql1
    ports:
      - "8080:8080"
    networks:
      - score_network
    environment:
      USER_SCORE_JDBC_URL: "jdbc:mysql://mysql1:3306/userscore?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      VIACEP_URL: https://viacep.com.br/ws/
      SCORE_API_URL: http://score-server:8081/score
      MAIL_HOST_HOTMAIL: smtp.office365.com
      MAIL_PORT: 587
      TOKEN_MAIL_USERNAME: ${TOKEN_MAIL_USERNAME}
      TOKEN_MAIL_PASSWORD: ${TOKEN_MAIL_PASSWORD}
      ENVIAR_EMAIL: true
      APP_FILE_PATH: /app/usuarios_scores.txt

  score-server:
    image: "score-api-server"
    container_name: "score-server"
    ports:
      - "8081:8081"
    networks:
      - score_network
    volumes:
      - C:/Users/bruno/Desktop/user-score/usuarios_scores.txt:/app/usuarios_scores.txt

networks:
  score_network:
    external: true

volumes:
  mysql_data:
